# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: rramo012
          repo: testing-release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: 'https://wiki.central.inmotionhosting.com/graphql'
          headers: '{"Authorization": "bearer ${{ secrets.CENTRAL_WIKIJS_TOKEN }}", "Content-type": "application/json" }'
          operation_name: Page
          verbose: true
          method: post
          graphql: |
            mutation Page {
              pages {
                create (
                    title: "Release - ${{ steps.get_latest_release.outputs.data.tag_name }}",
                    content: "${{ steps.get_latest_release.outputs.data.body }}",
                    description: "descrizione",
                    editor: "code",
                    isPublished: true, 
                    isPrivate: false, 
                    locale: "en", 
                    path:"/release/Angular-56446565gfggfd41", 
                    tags: [], 
                ) {
                  responseResult {
                    succeeded,
                  }
                }
              }
            }
